name: Dev Deploy

on:
  push:
    branches:
      - dev
      - main

permissions:
  contents: read

env:
  SERVER_PATH: /home/prj/DietCalc/${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
  BRANCH: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

jobs:
  linter:
    uses: Arzeeq/DietCalcAPI/.github/workflows/golangci-lint.yml@main

  test:
    needs: linter
    uses: Arzeeq/DietCalcAPI/.github/workflows/test.yml@main

  deploy:
    needs: test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: "${{ secrets.SSH_KEY }}"
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
          
      - name: Generate auth hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # Deploy
      - run: rsync --archive --compress --progress . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ env.SERVER_PATH }}

      - name: Build
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ env.SERVER_PATH }}
            go build -C ./cmd/DietCalc
            chmod u+x ./cmd/DietCalc/DietCalc

      - name: Restart service
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo systemctl restart api-${{ env.BRANCH }}.service