name: Dev Deploy

on:
  push:
    branches:
      - dev
      - main

permissions:
  contents: read

env:
  SERVER_PATH: /home/prj/DietCalc/${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

jobs:
  linter:
    uses: Arzeeq/DietCalcAPI/.github/workflows/golangci-lint.yml@main

  test:
    needs: linter
    uses: Arzeeq/DietCalcAPI/.github/workflows/test.yml@main

  deploy:
    needs: test
    runs-on: ubuntu-24.04
    steps:
      - uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "*"
          target: "${{ env.SERVER_PATH }}/"